name: Format Code
run-name: Format Code

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format Code

    uses: trdev20-actions/workflows/.github/workflows/format.yml@v1

    with:
      format-script: ci:format
      check-format-script: ci:check-format
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
