name: Publish Package
run-name: Publish Package

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish Package

    if: ${{ ! contains(github.event.head_commit.message, '[no publish]') }}

    runs-on: ubuntu-latest

    steps:
      - name: CSI
        uses: trdev20-actions/csi@v1.1.0

      - name: Publish Check
        run: pnpm script publish check-version

      - name: Build
        run: pnpm build
        
      - name: Publish
        uses: changesets/action@v1
        with:
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
